# Generated by Django 4.0.4 on 2022-05-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoOfWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizzId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('walletAddress', models.CharField(max_length=255)),
                ('whoReferedMe', models.CharField(blank=True, max_length=255, null=True)),
                ('myRefrealCode', models.CharField(blank=True, max_length=255, null=True)),
                ('isKycVerified', models.CharField(blank=True, default='False', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionHeading', models.CharField(max_length=255)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('weekId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INDIGGator.noofweeks')),
            ],
        ),
        migrations.CreateModel(
            name='KYCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('IdNumber', models.CharField(max_length=255)),
                ('documentFile', models.FileField(upload_to='Files/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INDIGGator.user')),
            ],
        ),
    ]
