# Generated by Django 4.0.4 on 2022-05-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referralCode',
            new_name='myRefrealCode',
        ),
        migrations.AddField(
            model_name='user',
            name='isKycVerified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whoReferedMe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
