# Generated by Django 4.0.4 on 2022-05-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INDIGGator.user')),
            ],
        ),
        migrations.CreateModel(
            name='courseCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isWeek1Completed', models.BooleanField(default=False)),
                ('isWeek2Completed', models.BooleanField(default=False)),
                ('isWeek3Completed', models.BooleanField(default=False)),
                ('isWeek4Completed', models.BooleanField(default=False)),
                ('score', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INDIGGator.user')),
            ],
        ),
    ]
