# Generated by Django 4.0.4 on 2022-05-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0002_rename_referralcode_user_myrefrealcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isKycVerified',
            field=models.BooleanField(blank=True, default='False', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='KYCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255)),
                ('IdNumber', models.CharField(max_length=255)),
                ('documentFile', models.FileField(upload_to='Files/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INDIGGator.user')),
            ],
        ),
    ]
