# Generated by Django 4.0.4 on 2022-05-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0003_user_twitterhandle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='user',
        ),
    ]
