# Generated by Django 4.0.4 on 2022-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0003_alter_user_iskycverified_kycdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isKycVerified',
            field=models.CharField(blank=True, default='False', max_length=255, null=True),
        ),
    ]
