# Generated by Django 4.0.4 on 2022-05-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0004_remove_games_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
