# Generated by Django 4.0.4 on 2022-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0004_alter_user_iskycverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionHeading', models.CharField(max_length=255)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
