# Generated by Django 4.0.4 on 2022-05-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0005_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
