# Generated by Django 4.0.4 on 2022-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INDIGGator', '0005_delete_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecompleted',
            name='score',
        ),
        migrations.AddField(
            model_name='coursecompleted',
            name='score1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursecompleted',
            name='score2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursecompleted',
            name='score3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursecompleted',
            name='score4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
